### ISSUE TITLE
Cache local data

### ISSUE THREAD

**Issue by MarkSRobinson** [aws/amazon-ec2-instance-selector#114]
Performance can be pretty bad when running queries and it's likely due to having to fetch data every time.

eg:

```
time ec2-instance-selector --memory-min 128 --vcpus-min 33 --cpu-architecture x86_64 -r us-east-1 -o table --max-results 200 --allow-list "m5\.*"

________________________________________________________
Executed in   21.87 secs      fish           external
   usr time  676.80 millis    0.25 millis  676.56 millis
   sys time  246.06 millis    1.39 millis  244.67 millis
```

I would be nice if the background data could be cached for a little while (5-60m would be a good default)

**Comment by bwagner5** [comment]
There's actually a PR out to do just that! It's been a long running PR since I was just doing it in the background because I wanted it faster, it's good to know others would also like it faster :)  

https://github.com/aws/amazon-ec2-instance-selector/pull/110 

I will be trying to finish this up soon!
