### ISSUE TITLE
Suppor/Flag to filter out burstable instances

### ISSUE THREAD

**Issue by ruecarlo** [aws/amazon-ec2-instance-selector#16]
While the flag `--burst-support` is great to list only burstable instances. I think there might be cases where adding some flag to only list non-burstable instances would be also helpful. For example, if my application has a mixed cpu/memory/io profile with high peaks of CPU now and again, I may prefer to avoid burstable instances.

For example: 
```
$ ec2-instance-selector --vcpus 4 --memory 16384 -a x86_64 --current-generation --non-burst-support
g4dn.xlarge
m4.xlarge
m5.xlarge
m5a.xlarge
m5ad.xlarge
m5d.xlarge
m5dn.xlarge
m5n.xlarge
```

Perhaps a more generic filtering out other attributes. Burstable instances however are probably the first that come to mind when thinking about production systems.

**Comment by bwagner5** [comment]
The boolean style flags accept a negative as well:

`--burst-support=false` will not show burstable instance types
`--baremetal=false` will not show baremetal instance types

In a similar respect:

`--gpus=0` will not show GPU instance types

Maybe a documentation update is needed rather than adding more flags?

**Comment by ruecarlo** [comment]
That makes total sense. Yes, I reckon additional documentation would be more than enough; Definitely no need to overcomplicate or add any extra flags !

**Comment by BLasan** [comment]
@ruecarlo Is this opened ?
