### ISSUE TITLE
Adding "Sorting" in the table-wide Mode

### ISSUE THREAD

**Issue by 4pits** [aws/amazon-ec2-instance-selector#21]
This is no doubt a cool addition to our toolset. Right now output is sorted by "Instance Type" 
**Requesting Add feature like "Sort By"  in the Table Wide mode.**
Can we add Sorting to sort by other variables ?

Something like 

> ec2-instance-selector --gpus 1 -o table-wide --sort m

_

**Comment by bwagner5** [comment]
@4pits sorry for the delayed reply! I definitely think it would be helpful to add sorting.  I'm wondering if the sort would also apply to the regular output as well.  One of the reasons it is sorted by instance-type is to make sure the response is deterministic between runs since the `max-results` is, by default, 20. Since the behind the scenes calls to the EC2 DescribeInstanceTypes API are paged, we needed a way to make sure results were consistent.

**Comment by digocorbellini** [comment]
@4pits Instance type sorting has now been implemented for all output formats! Checkout the readme for an example of its use: [CLI Examples](https://github.com/aws/amazon-ec2-instance-selector#cli)
